const MEAL_IMAGES: Record<string, ReturnType<typeof require>> = {
  'Arroz integral com feijão e frango': require('../../assets/meals/arroz-integral-com-feijao-e-frango.jpeg'),
  'Atum com arroz integral e legumes': require('../../assets/meals/atum-com-arroz-integral-e-legumes.jpeg'),
  'Atum com salada verde e azeite': require('../../assets/meals/atum-com-salada-verde-e-azeite.jpeg'),
  'Aveia com iogurte, banana e mel': require('../../assets/meals/aveia-com-iogurte-banana-e-mel.jpeg'),
  'Banana com iogurte grego': require('../../assets/meals/banana-com-iogurte-grego.jpeg'),
  'Banana com manteiga de amendoim': require('../../assets/meals/banana-com-manteiga-de-amendoim.jpeg'),
  'Carne moída com batata-doce e legumes': require('../../assets/meals/carne-moida-com-batata-doce-e-legumes.jpeg'),
  'Carne moída com macarrão integral': require('../../assets/meals/carne-moida-com-macarrao-integral.jpeg'),
  'Chá com banana pequena': require('../../assets/meals/cha-com-banana-pequena.jpeg'),
  'Claras de ovo mexidas com temperos': require('../../assets/meals/claras-de-ovo-mexidas-com-temperos.jpeg'),
  'Cottage com nozes e mel': require('../../assets/meals/cottage-com-nozes-e-mel.jpeg'),
  'Filé de frango com batata assada e legumes': require('../../assets/meals/file-de-frango-com-batata-assada-e-legumes.jpeg'),
  'Frango assado com arroz e brócolis': require('../../assets/meals/frango-assado-com-arroz-e-brocolis.jpeg'),
  'Frango assado com batata-doce e salada': require('../../assets/meals/frango-assado-com-batata-doce-e-salada.jpeg'),
  'Frango com chuchu e cenoura cozidos': require('../../assets/meals/frango-com-chuchu-e-cenoura-cozidos.jpeg'),
  'Frango com macarrão integral e legumes': require('../../assets/meals/frango-com-macarrao-integral-e-legumes.jpeg'),
  'Frango ensopado com legumes': require('../../assets/meals/frango-ensopado-com-legumes.jpeg'),
  'Frango grelhado com arroz e feijão': require('../../assets/meals/frango-grelhado-com-arroz-e-feijao.jpeg'),
  'Frango grelhado com salada e ovo': require('../../assets/meals/frango-grelhado-com-salada-e-ovo.jpeg'),
  'Frango ou carne com arroz, feijão e salada': require('../../assets/meals/frango-ou-carne-com-arroz-feijao-e-salada.jpeg'),
  'Fruta com pasta de amendoim': require('../../assets/meals/fruta-com-pasta-de-amendoim.jpeg'),
  'Frutas com mix de castanhas': require('../../assets/meals/frutas-com-mix-de-castanhas.jpeg'),
  'Frutas vermelhas com castanhas': require('../../assets/meals/frutas-vermelhas-com-castanhas.jpeg'),
  'Iogurte com frutas e canela': require('../../assets/meals/iogurte-com-frutas-e-canela.jpeg'),
  'Iogurte com granola e mel': require('../../assets/meals/iogurte-com-granola-e-mel.jpeg'),
  'Iogurte desnatado com canela': require('../../assets/meals/iogurte-desnatado-com-canela.jpeg'),
  'Iogurte grego com castanhas': require('../../assets/meals/iogurte-grego-com-castanhas.jpeg'),
  'Iogurte grego com granola': require('../../assets/meals/iogurte-grego-com-granola.jpeg'),
  'Iogurte grego com mel': require('../../assets/meals/iogurte-grego-com-mel.jpeg'),
  'Iogurte natural com frutas vermelhas e linhaça': require('../../assets/meals/iogurte-natural-com-frutas-vermelhas-e-linhaca.jpeg'),
  'Iogurte natural com whey e canela': require('../../assets/meals/iogurte-natural-com-whey-e-canela.jpeg'),
  'Leite morno com mel e canela': require('../../assets/meals/leite-morno-com-mel-e-canela.jpeg'),
  'Macarrão integral com molho bolonhesa': require('../../assets/meals/macarrao-integral-com-molho-bolonhesa.jpeg'),
  'Mingau proteico de aveia com frutas': require('../../assets/meals/mingau-proteico-de-aveia-com-frutas.jpeg'),
  'Omelete com abacate e café': require('../../assets/meals/omelete-com-abacate-e-cafe.jpeg'),
  'Omelete com batata-doce e legumes': require('../../assets/meals/omelete-com-batata-doce-e-legumes.jpeg'),
  'Omelete de claras com espinafre': require('../../assets/meals/omelete-de-claras-com-espinafre.jpeg'),
  'Omelete de queijo minas': require('../../assets/meals/omelete-de-queijo-minas.jpeg'),
  'Omelete misto com batata-doce': require('../../assets/meals/omelete-misto-com-batata-doce.jpeg'),
  'Ovos mexidos com aveia e banana': require('../../assets/meals/ovos-mexidos-com-aveia-e-banana.jpeg'),
  'Panqueca proteica de banana': require('../../assets/meals/panqueca-proteica-de-banana.jpeg'),
  'Pão integral com ovo e abacate': require('../../assets/meals/pao-integral-com-ovo-e-abacate.jpeg'),
  'Pão integral com pasta de atum': require('../../assets/meals/pao-integral-com-pasta-de-atum.jpeg'),
  'Patinho grelhado com batata-doce e salada': require('../../assets/meals/patinho-grelhado-com-batata-doce-e-salada.jpeg'),
  'Peixe grelhado com arroz e salada': require('../../assets/meals/peixe-grelhado-com-arroz-e-salada.jpeg'),
  'Peixe grelhado com legumes no vapor': require('../../assets/meals/peixe-grelhado-com-legumes-no-vapor.jpeg'),
  'Pepino com pasta de ricota e ervas': require('../../assets/meals/pepino-com-pasta-de-ricota-e-ervas.jpeg'),
  'Salmão com quinoa e brócolis': require('../../assets/meals/salmao-com-quinoa-e-brocolis.jpeg'),
  'Salmão grelhado com quinoa e espinafre': require('../../assets/meals/salmao-grelhado-com-quinoa-e-espinafre.jpeg'),
  'Sanduíche proteico integral': require('../../assets/meals/sanduiche-proteico-integral.jpeg'),
  'Shake de whey com aveia e banana': require('../../assets/meals/shake-de-whey-com-aveia-e-banana.jpeg'),
  'Tapioca com ovo e queijo minas': require('../../assets/meals/tapioca-com-ovo-e-queijo-minas.jpeg'),
  'Tapioca de ovo com café preto': require('../../assets/meals/tapioca-de-ovo-com-cafe-preto.jpeg'),
  'Tilápia assada com legumes coloridos': require('../../assets/meals/tilapia-assada-com-legumes-coloridos.jpeg'),
  'Torrada integral com ovo cozido': require('../../assets/meals/torrada-integral-com-ovo-cozido.jpeg'),
  'Torrada integral com ovo mexido e suco': require('../../assets/meals/torrada-integral-com-ovo-mexido-e-suco.jpeg'),
  'Torrada integral com queijo cottage': require('../../assets/meals/torrada-integral-com-queijo-cottage.jpeg'),
  'Torrada integral com ricota': require('../../assets/meals/torrada-integral-com-ricota.jpeg'),
  'Vitamina de banana com aveia e whey': require('../../assets/meals/vitamina-de-banana-com-aveia-e-whey.jpeg'),
  'Vitamina de banana com whey e pasta de amendoim': require('../../assets/meals/vitamina-de-banana-com-whey-e-pasta-de-amendoim.jpeg'),
}

export function getMealImage(name: string): ReturnType<typeof require> | null {
  return MEAL_IMAGES[name] ?? null
}
